#     _____                            _      _       _          ______
#    / ____|                          | |    (_)     | |        |___  /
#   | (___   ___ _ ____   _____ _ __  | |     _ _ __ | | _____     / /
#   \___ \ / _ \ '__\ \ / / _ \ '__| | |    | | '_ \| |/ / __|   / /
#   ____) |  __/ |   \ V /  __/ |    | |____| | | | |   <\__ \  / /__
#  |_____/ \___|_|    \_/ \___|_|    |______|_|_| |_|_|\_\___/ /_____|


# === COLOR CODES ===

# This plugin supports old color codes like: &c, &l, &o, etc.
# It also supports MiniMessage, a more advanced way to format messages:
# https://docs.advntr.dev/minimessage/format.html
# With MiniMessage, you can add HEX colors, gradients, hover and click events, etc.


# === GENERAL SETTINGS ===

# Set the language to any code found in the "lang" folder (don't add the .yml extension)
# You can add your own language files. Use https://github.com/KartoffelChipss/ServerLinksZ/tree/main/src/main/resources/lang/en-US.yml as a template
# If you want to share your language file, either create a pull request on GitHub or use GitLocalize: https://gitlocalize.com/repo/9890
#  | en-US | de-DE | zh-CN | ru-RU | zh-TW
lang: "en-US"

# Wether to show hints when using commands
hints: true

# Add a /link command to view the links
linkCommand: true

# [!!!] You can configure the links in the links.yml file!